{% set name = "flake8-pytest-style" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-pytest-style-{{ version }}.tar.gz
  sha256: c1175713e9e11b78cd1a035ed0bca0d1e41d09c4af329a952750b61d4194ddac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - flake8-plugin-utils >=1.3.2,<2.0.0
    - python >=3.6

test:
  imports:
    - flake8_pytest_style
    - flake8_pytest_style.visitors
  commands:
    - pip check
    - flake8 --version | grep flake8-pytest-style
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://pypi.org/project/flake8-pytest-style
  summary: A flake8 plugin checking common style issues or inconsistencies with pytest-based tests.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
